Dwitter2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('allauth.urls')),
]

base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('like/', views.like_post, name='like_post'),
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name="register")
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=15, unique=True)
    name = models.CharField(max_length=25, null=True)
    avatar = models.ImageField(null=True, default='/static/avatars/avatar.svg')
    bio = models.CharField(null=True, max_length=250)
    email = models.EmailField(null=True, unique=True)
    follow = models.ManyToManyField(
        'self', blank=True, symmetrical=False, related_name='user_follow')
    followers = models.ManyToManyField(
        'self', blank=True, symmetrical=False, related_name='user_followers'
    )
    has_posts = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return self.username

    @property
    def num_followers(self):
        return self.followers.all().count()


class Post(models.Model):
    host = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='host')
    body = models.CharField(max_length=50, null=False)
    created = models.DateTimeField(auto_now_add=True)
    liked = models.ManyToManyField(
        User, default=None, blank=True, related_name='liked',
    )
    bookmarked = models.ManyToManyField(User, default=None, blank=True, related_name='bookmarked')

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.body

    @property
    def num_likes(self):
        return self.liked.all().count()


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES,
                             default='Like', max_length=6)

    def __str__(self):
        return self.post


BOOKMARK_CHOICES = (
    ('Bookmark', 'Bookmark'),
    ('Un_bookmark', 'Un_bookmark')
)


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=BOOKMARK_CHOICES, default='Bookmark', max_length=11)


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.CharField(max_length=50, null=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

base/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from base.models import Post, Like, User
from django.contrib.auth.decorators import login_required
from .forms import UserForm, MyUserCreationForm
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm


def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, 'Username or Password does not exist')

    return render(request, 'base/login_register.html', {'page': page})


def logoutUser(request):
    logout(request)
    return redirect('base:home')


def registerPage(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('base:home')
        else:
            messages.error(request, 'An error occurred during registration')

    return render(request, 'base/login_register.html', {'form': form})


@login_required(login_url='base:login')
def home(request):
    posts = Post.objects.all()
    user = request.user
    context = {
        'posts': posts,
        'user': user,
    }
    return render(request, 'base/home.html', context)


def like_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)

        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)

        like, created = Like.objects.get_or_create(user=user, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()
    return redirect('base:home')

base/templates/base/home.html
{% extends 'main.html' %} {% block content %}

<div class="middle-side">
  <p class="page-name">Home</p>
  <textarea class="textarea" id="autoresizing">
      What's happening?
  </textarea>
  <div class="input-field-menu">
    <div class="input-options"></div>
    <div class="mid-tweet-button-container">
      <button class="mid-tweet-button">Tweet</button>
    </div>
  </div>
  {% for post in posts %}
  <div class="post-container">
    <div class="tweet-input-avatar">
      <button class="tweet-input-avatar-button">
        <img
          class="tweet-input-avatar-button-icon"
          src="{{post.host.avatar.url}}"
          alt=""
        />
      </button>
    </div>
    <div class="post-info-container">
      <div class="a">
        <span class="post-info-name">{{post.host.name}}</span>
        <span class="post-info-username-and-date">@{{post.host.username}}</span>
        <span class="post-info-username-and-date">&#183;</span>
        <span class="post-info-username-and-date">{{post.created}}</span>
      </div>
      <div class="b">
        <span class="post-info-text">{{post.body}}</span>
      </div>
      <div class="c">
        <div class="post-buttons-container">
          <form
            action="{% url 'base:like_post' %}"
            method="POST"
            class="like_post"
          >
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{post.id}}" />
            <!-- {% if user not in post.liked.all %} -->
            <!-- <button class="like_button_positive" type="submit">Like</button> -->
            <!-- {% else %} -->
            <!-- <button class="like_button_negative" type="submit">Unlike</button>
            {% endif %} -->
            <button class="like_button_like" type="submit">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                class="bi bi-heart"
                viewBox="0 0 16 16"
              >
                <path
                  d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"
                />
              </svg>
            </button>

            <span class="like_button_likes_count"> {{post.liked.all.count}} likes</span>
          </form>
        </div>
        <div class="post-buttons-container">fff</div>
        <div class="post-buttons-container">fff</div>
        <div class="post-buttons-container">fff</div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<div class="right-side"></div>

<script type="text/javascript">
  textarea = document.querySelector("#autoresizing");
  textarea.addEventListener("input", autoResize, false);

  function autoResize() {
    this.style.height = "auto";
    this.style.height = this.scrollHeight + "px";
  }
</script>

{% endblock content %}

base/templates/base/login_register.html
{% extends 'main.html' %} {% block content %} {% if page == 'login' %}

<div>
  <form method="POST" action="">
    {% csrf_token %}
    <label>Username: : </label>
    <input type="text" name="username" placeholder="Enter Username" />
    <label>Password:</label>
    <input type="password" name="password" placeholder="Enter Password" />
    <input type="submit" value="Login" />
  </form>

  <p>Haven't signed up yet?</p>
  <a href="http://127.0.0.1:8000/register/">Sign Up</a>
</div>

{% else %}

<div>
  <form action="" method="POST">
    {% csrf_token %} {% for field in form %}
    <div>
      <label>{{field.label}}</label>
      {{field}}
    </div>
    {% endfor %}

    <button class="btn btn--main" type="submit">
      <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
      >
        <title>lock</title>
        <path
          d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
        ></path>
        <path
          d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
        ></path>
      </svg>

      Register
    </button>
  </form>

  <p>Already signed up?</p>
  <a href="http://127.0.0.1:8000/login/">Login</a>
</div>
{% endif %} {% endblock content %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Dwitter</title>
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml version="1.0" standalone="no"?>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Mulish:wght@200&family=Roboto:wght@300;400;500;700&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/styles/main.css" />
    <link rel="stylesheet" href="/static/styles/navbar.css" />
  </head>
  <body>
    <div class="webpage-container">
      <!-- NAVBAR STARTS -->
      {% include 'navbar.html' %}
      <!-- NAVBAR ENDS -->

      {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li></li>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}


      <div class="webpage">
      {% block content %}

      {% endblock content %}

      </div>
    </div>
  </body>
</html>

templates/navbar.html
<div class="navbar-wrap">
  <div class="navbar">
    <div class="navbar-buttons-container">
      <button class="logo-button">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="34.38"
          height="29.07"
          fill="currentColor"
          class="bi bi-twitter"
          viewBox="0 0 16 16"
        >
          <path
            d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"
          />
        </svg>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/home.png"
            alt=""
          />
        </span>
        <span class="buttons-text">Home</span>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/notifications.png"
            alt=""
          />
        </span>
        <span class="buttons-text">Notifications</span>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/message.png"
            alt=""
          />
        </span>
        <span class="buttons-text">Messages</span>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/bookmark.png"
            alt=""
          />
        </span>
        <span class="buttons-text">Bookmarks</span>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/hashtag.png"
            alt=""
          />
        </span>
        <span class="buttons-text">Explore</span>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/profile.png"
            alt=""
          />
        </span>
        <span class="buttons-text">Profile</span>
      </button>
      <button class="buttons">
        <span class="buttons-icon">
          <img
            class="icon-size"
            src="/static/images/icons/more.png"
            alt=""
          />
        </span>
        <span class="buttons-text">More</span>
      </button>

      <!-- User Panel -->
      <div class="user-panel">
        <button class="profile-button">
          <div class="avatar">
            <img
              class="user-avatar"
              src="{{request.user.avatar.url}}"
              alt=""
            />
          </div>
          <div class="user-info">
            <p class="name">{{user.name}}</p>
            <p class="nickname">{{user.username}}</p>
          </div>
          <div class="user-button-icon">
            <i class="gg-more-alt"></i>
          </div>
        </button>
      </div>
    </div>
  </div>
</div>